build-steps:
  - build:
      type: script
      script:
        - set -x
        - mount
        - df -h
        - du -sh
        - dd if=/dev/zero of=zero bs=1M count=100
        - df -h
        - du -sh
