build-steps:
  - build:
      type: script
      script:
        - composer install --no-progress
        - echo "require('/var/www/site-php/bjfree/${PIPELINE_CLOUD_SITE}-settings.inc');" >> docroot/sites/default/settings.php
