version: 1.0.0

services:
  - mysql

events:
  build:
    steps:
      - install:
          type: script
          script:
            - 'composer --no-interaction --quiet install'
            - 'sudo /etc/init.d/mysql start'
            - 'mysql -u root -proot -e "CREATE DATABASE drupal"'
            - 'cd docroot'
            - '/usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" ../vendor/bin/drush site-install -y --db-url=mysql://root:root@127.0.0.1:3306/drupal'
            - 'php -S 127.0.0.1:8081 &'
            - 'sleep 2'
            - 'cd ..'
            - ./vendor/bin/behat
