version: 1.0.0

variables:
  global:
    PHP_OPTIONS: '-d sendmail_path=/bin/true'
    DB_URL: 'mysql://root:root@127.0.0.1:3306/drupal'

services:
  - mysql

events:
  build:
    steps:
      - build:
          type: script
          script:
            - composer install
      - test:
          type: script
          script:
            - mysql -u root -proot -e "CREATE DATABASE drupal"
            - cd docroot
            - ../bin/drush site-install -y --db-url=$DB_URL
            - php -S 127.0.0.1:8080 &
            - cd ..
            - sleep 2
            - ./bin/behat
